### ISSUE TITLE
[DEP0132] DeprecationWarning: Passing a callback to worker.terminate() is deprecated. It returns a Promise instead.

### ISSUE THREAD

**Issue by Trott** [idan-at/thread-pool-node#1]
In current Node.js, this code in this package:

https://github.com/idan-at/thread-pool-node/blob/435ecdce2069a3735445839b62644be24e3882a6/index.js#L8-L13

...results in the deprecation warning:

```
[DEP0132] DeprecationWarning: Passing a callback to worker.terminate() is deprecated. It returns a Promise instead.
```

**Comment by idan-at** [comment]
@Trott issue is resolved in 1.0.8.
